[package]
name = "wow-formats"
version = "0.1.0"
edition = "2021"

[dependencies]
wow-math = { path = "../wow-math" }
wow-common = { path = "../wow-common" }
wow-assets = { path = "../wow-assets" }
wow-mpq = { workspace = true }
wow-blp = { workspace = true }
wow-adt = { workspace = true }
wow-m2 = { workspace = true }
wow-wmo = { workspace = true }
wow_dbc = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
byteorder = { workspace = true }
