[package]
name = "wow-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
wow-common = { path = "../wow-common" }
wow-math = { path = "../wow-math" }
wow_world_messages = { workspace = true }
wow_login_messages = { workspace = true }
byteorder = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
